include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/src/**/*.g.dart
    - lib/src/**/*.freezed.dart
    - lib/src/api/proto/**/*.dart
    - lib/**/*.swagger*dart

linter:
  rules:
    always_use_package_imports: true
    directives_ordering: true
    prefer_interpolation_to_compose_strings: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
    invalid_annotation_target: false
