targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - swaggers2/**
      - swagger_examples/**
      - $package$
    builders:
      freezed:
          options:
            generic_argument_factories: true
      chopper_generator:
        options:
          header: "// Generated code - do not change"
      swagger_dart_code_generator:
        options:
          with_converter: true
          input_folder: "lib/swaggers"
          output_folder: "lib/src/rest/"
          enums_case_sensitive: true
          include_if_null: true