name: nakama
description: Nakama is an open-source scalable game server that lets you focus
  on building games.
version: 1.0.1
repository: https://github.com/obrunsmann/flutter_nakama
homepage: https://flutter-nakama.gitbook.io

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  chopper: ^7.0.4
  collection: ^1.17.0
  fixnum: ^1.1.0
  freezed_annotation: ^2.4.1
  grpc: ^3.2.3
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  logging: ^1.2.0
  meta: ^1.9.1
  protobuf: ^3.1.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.6
  chopper_generator: ^7.0.2
  faker: ^2.1.0
  flutter_lints: ^2.0.2
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  swagger_dart_code_generator: ^2.11.10
  test: ^1.24.6
